### ISSUE TITLE
please tag a release (10.0.1?) with #252 included

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [nix-community/crate2nix#264]
Hi, `dep:crate` dependencies are starting to appear in projects.  Fortunately crate2nix is ahead of the game!  #252 added support for these.  Would it be possible to tag a minor release somewhere after that merge so I can submit a PR to bump the crate2nix in nixpkgs?

Aside from needing #252, crate2nix does a wonderful job of building [tvix](https://tvl.fyi/blog/tvix-status-september-22); the following "just works" with ca2aef6de460a428e79d3920150fbe74aca87fdc:

```
git clone https://code.tvl.fyi/depot.git
cd depot/tvix/eval
crate2nix generate
nix build -f Cargo.nix -L rootCrate
result/bin/tvix-eval --expr 'let nix = "is so"; in with { nix = "crazy"; }; nix'
```

> `=> "is so" :: string`

**Comment by amjoseph-nixpkgs** [comment]
See also https://cl.tvl.fyi/c/depot/+/7350

**Comment by Ericson2314** [comment]
I pushed some tags for a release candidate. @kolloch is there anything I should do as part of cutting an actual release?

**Comment by bouk** [comment]
@Ericson2314 it seems to me that tagging the release is all that's needed, then it can be bumped in nixpkgs 😃

**Comment by amjoseph-nixpkgs** [comment]
Ping.

**Comment by amjoseph-nixpkgs** [comment]
Hi, it's been almost a full year.

Could somebody please tag a release so we can get #252 into the 23.11 release of nixpkgs?  An increasingly-large number of crates are broken without that.

**Comment by kolloch** [comment]
> I pushed some tags for a release candidate. @kolloch is there anything I should do as part of cutting an actual release?

Sorry for missing these. I was hesitant to release because tests have been broken for Mac OS for a while. I recently fixed those.

There are some steps that I tend to do on release here:

https://github.com/nix-community/crate2nix/blob/master/release-steps.md

I should probably update them to a more modern workflow.

**Comment by amjoseph-nixpkgs** [comment]
Thank you!
