### ISSUE TITLE
`CARGO_MANIFEST_LINKS` environment variable missing in build environment

### ISSUE THREAD

**Issue by MangoIV** [nix-community/crate2nix#300]
I have a dependency that looks at `CARGO_MANIFEST_LINKS` env var (within `build.rs`) but this is not set withing the build environment that is generated by `crate2nix`. As it is available when building with `cargo`, I think it should be set by the `cargo2nix` build environment as well.

**Comment by jamessewell** [comment]
I'm seeing this as well, any idea how you would fix this?
